name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
jobs:
  license_tests:
    uses: neongeckocom/.github/.github/workflows/license_tests.yml@master
